name: publish-docs

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
  pull_request:
    branches:
      - 'main'

env:
  NODE_VERSION: 18.16.0 # renovate: datasource=node depName=node
  PYTHON_VERSION: 3.11.3 # renovate: datasource=github-releases depName=python packageName=containerbase/python-prebuild
  # Don't use PIPENV_VERSION:  https://github.com/pypa/pipenv/issues/3633#issuecomment-478250721
  RENOVATE_PIPENV_VERSION: 2023.5.19 # renovate: datasource=pypi depName=pipenv

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'

      - name: Init platform
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name  'Renovate Bot'
          python --version
          pip install pipenv==${{ env.RENOVATE_PIPENV_VERSION }}
          pipenv --version

      - name: Installing dependencies
        run: make install

      - name: Run Prettier
        run: yarn prettier

      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@f52d78284b4941028952125a10c76676c3d456eb # v1.17.0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          path: |
            bin
            .husky
          pattern: '*.sh'
          check_all_files_with_shebangs: 'true'

      - name: Prepare docs
        run: make prepare

      - name: Build cache decoder
        run: make build-decoder

      - name: Build docs
        run: make build-docs

      - name: Upload site artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: site
          path: site/
          if-no-files-found: error

      - name: Cypress run
        uses: cypress-io/github-action@191187832803e908aa13b6e33c2c42abd8b12c5a # v5.8.0
        with:
          start: make serve
          wait-on: 'http://127.0.0.1:8000/'
          # we have already installed all dependencies above
          install: false
        timeout-minutes: 3

      - name: Upload cypress artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/
            cypress/screenshots/
          if-no-files-found: error

      - name: Publish docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make deploy
